In [2]:
import numpy as np
import cv2

cap=cv2.VideoCapture(0)
while(True):
    ret,frame=cap.read()
    print(frame)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) == ord('q'):
        print(cv2.waitKey(1))
        break
cap.release()
cv2.destroyAllWindows()

[[[ 81  62  52]
  [ 81  61  53]
  [ 81  61  53]
  ...
  [173 150 130]
  [174 151 131]
  [174 151 131]]

 [[ 79  60  50]
  [ 80  60  52]
  [ 81  61  53]
  ...
  [173 150 130]
  [173 150 130]
  [173 150 130]]

 [[ 77  55  47]
  [ 77  57  51]
  [ 77  58  52]
  ...
  [168 151 132]
  [167 150 131]
  [166 149 130]]

 ...

 [[ 22  53  68]
  [ 24  56  71]
  [ 24  59  72]
  ...
  [ 20  12  15]
  [ 21  13  16]
  [ 22  14  17]]

 [[ 22  50  68]
  [ 23  54  69]
  [ 26  59  72]
  ...
  [ 18  13  17]
  [ 17  14  18]
  [ 19  16  20]]

 [[ 20  48  66]
  [ 22  53  68]
  [ 26  59  72]
  ...
  [ 19  14  18]
  [ 18  15  19]
  [ 20  17  21]]]
[[[ 48  45  48]
  [ 47  44  48]
  [ 48  45  49]
  ...
  [164 145 135]
  [164 145 135]
  [164 145 135]]

 [[ 48  45  48]
  [ 48  45  49]
  [ 49  46  50]
  ...
  [165 146 136]
  [165 146 136]
  [165 146 136]]

 [[ 49  50  46]
  [ 52  50  48]
  [ 53  51  49]
  ...
  [168 147 137]
  [168 147 137]
  [169 148 138]]

 ...

 [[ 18  51  70]
  [ 17  50  69]
  [ 15  51  69]
  ..

[[[ 68  51  45]
  [ 75  58  52]
  [ 80  66  57]
  ...
  [167 157 148]
  [161 153 144]
  [158 150 141]]

 [[ 66  49  43]
  [ 72  55  49]
  [ 76  62  53]
  ...
  [166 156 147]
  [161 153 144]
  [159 151 142]]

 [[ 67  53  44]
  [ 71  57  48]
  [ 73  62  51]
  ...
  [166 155 142]
  [163 154 141]
  [162 153 140]]

 ...

 [[  0  50  65]
  [  0  48  64]
  [  2  50  66]
  ...
  [ 24  11   8]
  [ 22  11   6]
  [ 24  13   8]]

 [[  1  50  70]
  [  2  49  69]
  [  5  51  68]
  ...
  [ 23  10  14]
  [ 23  11  12]
  [ 25  13  14]]

 [[  5  54  74]
  [  6  53  73]
  [  8  54  71]
  ...
  [ 23  10  14]
  [ 24  12  13]
  [ 24  12  13]]]
[[[ 66  48  38]
  [ 67  51  41]
  [ 66  55  42]
  ...
  [177 153 145]
  [175 151 143]
  [174 150 142]]

 [[ 68  50  40]
  [ 68  52  42]
  [ 66  55  42]
  ...
  [177 153 145]
  [176 152 144]
  [175 151 143]]

 [[ 73  52  40]
  [ 72  53  41]
  [ 72  55  40]
  ...
  [174 154 146]
  [172 152 144]
  [172 152 144]]

 ...

 [[ 23  55  56]
  [ 26  56  57]
  [ 27  57  58]
  ..

[[[ 58  57  53]
  [ 47  49  51]
  [ 37  42  49]
  ...
  [184 155 141]
  [182 155 140]
  [181 154 139]]

 [[ 57  56  52]
  [ 47  49  51]
  [ 39  44  51]
  ...
  [180 151 137]
  [177 150 135]
  [176 149 134]]

 [[ 59  55  45]
  [ 54  51  45]
  [ 48  48  46]
  ...
  [175 149 131]
  [174 148 129]
  [173 147 128]]

 ...

 [[ 25  48  71]
  [ 24  47  69]
  [ 24  47  67]
  ...
  [ 23  13  14]
  [ 22  12  13]
  [ 22  12  13]]

 [[ 24  48  76]
  [ 24  48  74]
  [ 24  49  72]
  ...
  [ 34  11  19]
  [ 35  10  16]
  [ 35  10  16]]

 [[ 24  48  76]
  [ 25  49  75]
  [ 26  51  74]
  ...
  [ 33  10  18]
  [ 35  10  16]
  [ 35  10  16]]]
[[[ 58  57  53]
  [ 47  49  51]
  [ 37  42  49]
  ...
  [184 155 141]
  [182 155 140]
  [181 154 139]]

 [[ 57  56  52]
  [ 47  49  51]
  [ 39  44  51]
  ...
  [180 151 137]
  [177 150 135]
  [176 149 134]]

 [[ 59  55  45]
  [ 54  51  45]
  [ 48  48  46]
  ...
  [175 149 131]
  [174 148 129]
  [173 147 128]]

 ...

 [[ 25  48  71]
  [ 24  47  69]
  [ 24  47  67]
  ..

[[[ 71  48  26]
  [ 77  54  34]
  [ 80  57  37]
  ...
  [173 151 135]
  [174 152 136]
  [175 153 137]]

 [[ 72  49  27]
  [ 76  53  33]
  [ 78  55  35]
  ...
  [173 151 135]
  [174 152 136]
  [174 152 136]]

 [[ 70  51  29]
  [ 71  52  32]
  [ 73  54  34]
  ...
  [172 152 137]
  [172 152 137]
  [172 152 137]]

 ...

 [[ 23  54  68]
  [ 22  53  67]
  [ 23  54  68]
  ...
  [ 32  13  17]
  [ 31  14  18]
  [ 32  15  19]]

 [[ 27  52  64]
  [ 27  52  64]
  [ 29  55  64]
  ...
  [ 25  15  16]
  [ 24  16  17]
  [ 25  17  18]]

 [[ 23  48  60]
  [ 24  49  61]
  [ 28  54  63]
  ...
  [ 27  17  18]
  [ 25  17  18]
  [ 26  18  19]]]
[[[ 71  48  26]
  [ 77  54  34]
  [ 80  57  37]
  ...
  [173 151 135]
  [174 152 136]
  [175 153 137]]

 [[ 72  49  27]
  [ 76  53  33]
  [ 78  55  35]
  ...
  [173 151 135]
  [174 152 136]
  [174 152 136]]

 [[ 70  51  29]
  [ 71  52  32]
  [ 73  54  34]
  ...
  [172 152 137]
  [172 152 137]
  [172 152 137]]

 ...

 [[ 23  54  68]
  [ 22  53  67]
  [ 23  54  68]
  ..

[[[ 52  62  51]
  [ 47  59  50]
  [ 43  57  49]
  ...
  [164 150 149]
  [163 151 152]
  [164 152 153]]

 [[ 52  62  51]
  [ 48  60  51]
  [ 44  58  50]
  ...
  [164 150 149]
  [163 151 152]
  [164 152 153]]

 [[ 56  61  50]
  [ 53  59  51]
  [ 50  58  51]
  ...
  [171 152 146]
  [169 152 147]
  [170 153 148]]

 ...

 [[ 30  51  63]
  [ 33  52  64]
  [ 33  52  64]
  ...
  [ 38  13  18]
  [ 39  15  17]
  [ 40  16  18]]

 [[ 22  54  65]
  [ 26  53  67]
  [ 30  53  67]
  ...
  [ 26  12  20]
  [ 26  12  20]
  [ 27  13  21]]

 [[ 23  55  66]
  [ 27  54  68]
  [ 30  53  67]
  ...
  [ 26  12  20]
  [ 25  11  19]
  [ 25  11  19]]]
[[[ 52  62  51]
  [ 47  59  50]
  [ 43  57  49]
  ...
  [164 150 149]
  [163 151 152]
  [164 152 153]]

 [[ 52  62  51]
  [ 48  60  51]
  [ 44  58  50]
  ...
  [164 150 149]
  [163 151 152]
  [164 152 153]]

 [[ 56  61  50]
  [ 53  59  51]
  [ 50  58  51]
  ...
  [171 152 146]
  [169 152 147]
  [170 153 148]]

 ...

 [[ 30  51  63]
  [ 33  52  64]
  [ 33  52  64]
  ..

  [ 17  10  11]]]
[[[ 28  52  38]
  [ 36  52  43]
  [ 42  53  46]
  ...
  [176 145 140]
  [178 147 142]
  [180 149 144]]

 [[ 28  52  38]
  [ 36  52  43]
  [ 43  54  47]
  ...
  [178 147 142]
  [180 149 144]
  [182 151 146]]

 [[ 43  53  38]
  [ 47  54  42]
  [ 50  57  46]
  ...
  [174 150 141]
  [174 153 143]
  [176 155 145]]

 ...

 [[ 43  54  77]
  [ 41  52  75]
  [ 38  51  74]
  ...
  [ 21  12  17]
  [ 20  11  16]
  [ 20  11  16]]

 [[ 39  57  81]
  [ 37  55  79]
  [ 33  53  77]
  ...
  [ 18  11  14]
  [ 18  11  12]
  [ 19  12  13]]

 [[ 39  57  81]
  [ 37  55  79]
  [ 33  53  77]
  ...
  [ 17  10  13]
  [ 17  10  11]
  [ 17  10  11]]]
[[[ 59  52  56]
  [ 59  52  56]
  [ 57  52  56]
  ...
  [176 145 131]
  [179 148 134]
  [182 151 137]]

 [[ 62  55  59]
  [ 61  54  58]
  [ 59  54  58]
  ...
  [177 146 132]
  [179 148 134]
  [181 150 136]]

 [[ 64  58  56]
  [ 62  56  54]
  [ 59  55  53]
  ...
  [174 148 139]
  [175 149 140]
  [176 150 141]]

 ...

 [[ 23  54  71]
  [ 23  54  71]
  

[[[ 78  55  53]
  [ 73  51  51]
  [ 67  49  48]
  ...
  [158 153 147]
  [158 155 149]
  [160 157 151]]

 [[ 76  53  51]
  [ 72  50  50]
  [ 66  48  47]
  ...
  [159 154 148]
  [158 155 149]
  [159 156 150]]

 [[ 70  52  50]
  [ 69  51  49]
  [ 65  49  47]
  ...
  [166 154 147]
  [166 154 147]
  [167 155 148]]

 ...

 [[ 13  56  72]
  [ 13  56  72]
  [ 12  55  71]
  ...
  [ 27  15  16]
  [ 24  14  15]
  [ 23  13  14]]

 [[ 14  54  71]
  [ 14  54  72]
  [ 13  53  71]
  ...
  [ 26  14  13]
  [ 26  15  12]
  [ 26  15  12]]

 [[ 14  54  71]
  [ 14  54  72]
  [ 13  53  71]
  ...
  [ 27  15  14]
  [ 26  15  12]
  [ 26  15  12]]]
[[[ 67  46  36]
  [ 62  46  37]
  [ 54  46  39]
  ...
  [172 152 150]
  [172 152 150]
  [172 152 150]]

 [[ 65  44  34]
  [ 60  44  35]
  [ 53  45  38]
  ...
  [170 150 148]
  [170 150 148]
  [171 151 149]]

 [[ 60  42  41]
  [ 55  43  42]
  [ 51  45  42]
  ...
  [168 148 146]
  [169 149 147]
  [169 149 147]]

 ...

 [[ 37  49  66]
  [ 38  50  67]
  [ 38  53  68]
  ..

[[[ 46  52  59]
  [ 48  54  61]
  [ 49  55  62]
  ...
  [168 146 138]
  [166 146 138]
  [168 148 140]]

 [[ 45  51  58]
  [ 46  52  59]
  [ 47  53  60]
  ...
  [168 146 138]
  [166 146 138]
  [167 147 139]]

 [[ 45  52  54]
  [ 46  53  55]
  [ 46  53  55]
  ...
  [172 145 140]
  [170 145 140]
  [172 147 142]]

 ...

 [[ 36  53  69]
  [ 37  53  72]
  [ 38  55  74]
  ...
  [ 18  10  17]
  [ 19  12  16]
  [ 19  12  16]]

 [[ 30  54  80]
  [ 34  56  82]
  [ 37  59  85]
  ...
  [ 19  11  26]
  [ 19  12  24]
  [ 19  12  24]]

 [[ 30  54  80]
  [ 35  57  83]
  [ 37  59  85]
  ...
  [ 20  12  27]
  [ 19  12  24]
  [ 19  12  24]]]
[[[ 50  53  60]
  [ 49  52  59]
  [ 47  50  56]
  ...
  [156 147 144]
  [153 146 143]
  [152 145 142]]

 [[ 48  51  58]
  [ 47  50  57]
  [ 47  50  56]
  ...
  [156 147 144]
  [153 146 143]
  [152 145 142]]

 [[ 49  51  51]
  [ 51  51  51]
  [ 52  52  52]
  ...
  [159 147 140]
  [157 147 140]
  [157 147 140]]

 ...

 [[ 12  54  72]
  [ 13  55  73]
  [ 14  56  74]
  ..

In [19]:
cap=cv2.VideoCapture(0)
cap.set(3,800)
cap.set(4,900)
while(True):
    ret,frame=cap.read()
    #print(frame)
    frame = cv2.flip(frame,1)
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) == ord('q'):
        print(cv2.waitKey(1))
        break
cap.release()
cv2.destroyAllWindows()

-1


In [34]:
#Saving a video
cap=cv2.VideoCapture(0)

fourcc=cv2.VideoWriter_fourcc(*'XVID')
out=cv2.VideoWriter('First_Video.avi',fourcc,30.0,(700,500))
while(cap.isOpened()):
    ret,frame=cap.read()
    if ret==True:
        frame=cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow('frame',frame)
        if cv2.waitKey(1) == ord('q'):
        
            break
    else:
        break
cap.release()
out.release()
cv2.destroyAllWindows()
        
        zdfsdasdasdad

In [30]:

cap = cv2.VideoCapture('First_Video.avi')

while(cap.isOpened()):
    ret, frame = cap.read()
    
  

    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-kh7iq4w7\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
